"""empty message

Revision ID: 88296300011c
Revises: ddb66513234b
Create Date: 2022-12-11 12:19:31.840851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88296300011c'
down_revision = 'ddb66513234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_recipt_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipt_timestamp'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
