"""empty message

Revision ID: f6a76200c12a
Revises: 
Create Date: 2022-12-10 14:30:24.282245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a76200c12a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('recipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=4000), nullable=True),
    sa.Column('img_src', sa.String(length=120), nullable=True),
    sa.Column('total', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_src')
    )
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipt_total'), ['total'], unique=True)

    op.create_table('user_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipt_id', sa.Integer(), nullable=True),
    sa.Column('user_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipt_id'], ['recipt.id'], ),
    sa.ForeignKeyConstraint(['user_tag_id'], ['user_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('user_tag')
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipt_total'))

    op.drop_table('recipt')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
