"""empty message

Revision ID: f852e31c4753
Revises: cad8d96e718a
Create Date: 2022-12-10 15:08:33.199936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f852e31c4753'
down_revision = 'cad8d96e718a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.drop_column('store')

    # ### end Alembic commands ###
