"""empty message

Revision ID: fa9008b6259f
Revises: 88296300011c
Create Date: 2022-12-12 21:31:52.697409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9008b6259f'
down_revision = '88296300011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipt', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    op.drop_table('invite')
    # ### end Alembic commands ###
